### ISSUE TITLE
Watchtower not restarting containers after update

### ISSUE THREAD

**Issue by dorel14** [MRColorR/money4band#36] opened 2023-03-18 17:08 UTC
**Describe the bug**
Hello , toi day i was surprised that traffmonetizer and repocket  don't share anything  , i 'have tried to run runme.sh and i 've seen that these 2 containers are recreated .

Why watchtower has not done his job  ?

**Device (please complete the following information):**
 - Type:  Raspberry Pi 3 B+
 - OS details:  Linux raspbine
 - Platform:  arm64 (64bit) 
 - Version Raspbian Stretch
 
 **Docker**
 - Docker Compose version:   version v2.16.0
 - Docker version:  23.0.1

**To Reproduce**
Just let you docker container live and wait a new version of a container is published

**Expected behavior**
Normally WatchTower is here to make the update automaticaly 

**Screenshots**

**Additional context**`
WatchTower logs

~~~
time="2023-03-16T21:08:12Z" level=warning msg="Could not do a head request for \"repocket/repocket:latest\", falling back to regular pull." container=/repocket image="repocket/repocket:latest"
time="2023-03-16T21:08:12Z" level=warning msg="Reason: Get \"https://index.docker.io/v2/\": dial tcp: lookup index.docker.io on 127.0.0.11:53: read udp 127.0.0.1:53214->127.0.0.11:53: i/o timeout" container=/repocket image="repocket/repocket:latest"
time="2023-03-16T21:08:49Z" level=info msg="Unable to update container \"/repocket\": Error response from daemon: Get \"https://registry-1.docker.io/v2/\": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers). Proceeding to next."
time="2023-03-16T21:08:59Z" level=warning msg="Could not do a head request for \"proxyrack/pop:latest\", falling back to regular pull." container=/proxyrack image="proxyrack/pop:latest"
time="2023-03-16T21:08:59Z" level=warning msg="Reason: Get \"https://index.docker.io/v2/\": dial tcp: lookup index.docker.io on 127.0.0.11:53: read udp 127.0.0.1:32860->127.0.0.11:53: i/o timeout" container=/proxyrack image="proxyrack/pop:latest"
time="2023-03-16T21:09:35Z" level=info msg="Unable to update container \"/proxyrack\": Error response from daemon: Get \"https://registry-1.docker.io/v2/\": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers). Proceeding to next."
time="2023-03-16T21:09:45Z" level=warning msg="Could not do a head request for \"bitping/bitping-node:latest\", falling back to regular pull." container=/bitping image="bitping/bitping-node:latest"
time="2023-03-16T21:09:45Z" level=warning msg="Reason: Get \"https://index.docker.io/v2/\": dial tcp: lookup index.docker.io on 127.0.0.11:53: read udp 127.0.0.1:58190->127.0.0.11:53: i/o timeout" container=/bitping image="bitping/bitping-node:latest"
time="2023-03-16T21:10:28Z" level=info msg="Unable to update container \"/bitping\": Error response from daemon: Get \"https://registry-1.docker.io/v2/\": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers). Proceeding to next."
time="2023-03-16T21:10:38Z" level=warning msg="Could not do a head request for \"fazalfarhan01/earnapp:lite\", falling back to regular pull." container=/earnapp image="fazalfarhan01/earnapp:lite"
time="2023-03-16T21:10:38Z" level=warning msg="Reason: Get \"https://index.docker.io/v2/\": dial tcp: lookup index.docker.io on 127.0.0.11:53: read udp 127.0.0.1:42925->127.0.0.11:53: i/o timeout" container=/earnapp image="fazalfarhan01/earnapp:lite"
time="2023-03-16T21:11:18Z" level=info msg="Unable to update container \"/earnapp\": Error response from daemon: Get \"https://registry-1.docker.io/v2/\": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers). Proceeding to next."
time="2023-03-16T21:11:28Z" level=warning msg="Could not do a head request for \"peer2profit/peer2profit_linux:latest\", falling back to regular pull." container=/peer2profit image="peer2profit/peer2profit_linux:latest"
time="2023-03-16T21:11:28Z" level=warning msg="Reason: Get \"https://index.docker.io/v2/\": dial tcp: lookup index.docker.io on 127.0.0.11:53: read udp 127.0.0.1:39565->127.0.0.11:53: i/o timeout" container=/peer2profit image="peer2profit/peer2profit_linux:latest"
time="2023-03-16T21:12:10Z" level=info msg="Unable to update container \"/peer2profit\": Error response from daemon: Get \"https://registry-1.docker.io/v2/\": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers). Proceeding to next."
time="2023-03-16T21:12:20Z" level=warning msg="Could not do a head request for \"honeygain/honeygain:latest\", falling back to regular pull." container=/honeygain image="honeygain/honeygain:latest"
time="2023-03-16T21:12:20Z" level=warning msg="Reason: Get \"https://index.docker.io/v2/\": dial tcp: lookup index.docker.io on 127.0.0.11:53: read udp 127.0.0.1:58422->127.0.0.11:53: i/o timeout" container=/honeygain image="honeygain/honeygain:latest"
time="2023-03-16T21:12:55Z" level=info msg="Unable to update container \"/honeygain\": Error response from daemon: Get \"https://registry-1.docker.io/v2/\": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers). Proceeding to next."
time="2023-03-16T21:13:05Z" level=warning msg="Could not do a head request for \"iproyal/pawns-cli:latest\", falling back to regular pull." container=/iproyal image="iproyal/pawns-cli:latest"
time="2023-03-16T21:13:05Z" level=warning msg="Reason: Get \"https://index.docker.io/v2/\": dial tcp: lookup index.docker.io on 127.0.0.11:53: read udp 127.0.0.1:40218->127.0.0.11:53: i/o timeout" container=/iproyal image="iproyal/pawns-cli:latest"
time="2023-03-16T21:13:42Z" level=info msg="Unable to update container \"/iproyal\": Error response from daemon: Get \"https://registry-1.docker.io/v2/\": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers). Proceeding to next."
time="2023-03-16T21:13:52Z" level=warning msg="Could not do a head request for \"fnichol/uhttpd:latest\", falling back to regular pull." container=/webdashboard image="fnichol/uhttpd:latest"
time="2023-03-16T21:13:52Z" level=warning msg="Reason: Get \"https://index.docker.io/v2/\": dial tcp: lookup index.docker.io on 127.0.0.11:53: read udp 127.0.0.1:54894->127.0.0.11:53: i/o timeout" container=/webdashboard image="fnichol/uhttpd:latest"
time="2023-03-16T21:14:27Z" level=info msg="Unable to update container \"/webdashboard\": Error response from daemon: Get \"https://registry-1.docker.io/v2/\": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers). Proceeding to next."
time="2023-03-16T21:14:37Z" level=warning msg="Could not do a head request for \"packetstream/psclient:latest\", falling back to regular pull." container=/packetstream image="packetstream/psclient:latest"
time="2023-03-16T21:14:37Z" level=warning msg="Reason: Get \"https://index.docker.io/v2/\": dial tcp: lookup index.docker.io on 127.0.0.11:53: read udp 127.0.0.1:58471->127.0.0.11:53: i/o timeout" container=/packetstream image="packetstream/psclient:latest"
time="2023-03-16T21:15:13Z" level=info msg="Unable to update container \"/packetstream\": Error response from daemon: Get \"https://registry-1.docker.io/v2/\": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers). Proceeding to next."
time="2023-03-16T21:15:23Z" level=warning msg="Could not do a head request for \"containrrr/watchtower:latest\", falling back to regular pull." container=/watchtower image="containrrr/watchtower:latest"
time="2023-03-16T21:15:23Z" level=warning msg="Reason: Get \"https://index.docker.io/v2/\": dial tcp: lookup index.docker.io on 127.0.0.11:53: read udp 127.0.0.1:59740->127.0.0.11:53: i/o timeout" container=/watchtower image="containrrr/watchtower:latest"
time="2023-03-16T21:16:02Z" level=info msg="Unable to update container \"/watchtower\": Error response from daemon: Get \"https://registry-1.docker.io/v2/\": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers). Proceeding to next."

~~~

**Comment by dorel14** [comment] 2023-04-06 16:31
Thx for your answer , i close this and will reopen if needed

**Comment by dorel14** [comment] 2023-04-07 06:49
Hello 
I reopen and change the title of this issue

Yesterday i've seen that prooxyrack don't have shared anything on the dashboard 

![image](https://user-images.githubusercontent.com/10910133/230556454-2475addf-54c1-4b41-b300-5e5c21e2b384.png)
 
So i decided to have a look at they docker update 

![image](https://user-images.githubusercontent.com/10910133/230556587-177e7129-8430-4b6c-b0e9-3ba6f662b12a.png)

i get a look at my watchtower logs 

`docker logs --since 2023-04-05 watchtower`

Here is what i saw 
~~~
net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers). Proceeding to next."
time="2023-04-05T01:17:55Z" level=info msg="Session done" Failed=0 Scanned=11 Updated=0 notify=no
time="2023-04-05T03:12:17Z" level=info msg="Found new proxyrack/pop:latest image (f0a566a7fb6c)"
time="2023-04-05T03:12:19Z" level=info msg="Stopping /proxyrack (5ab41b02e06d) with SIGTERM"
time="2023-04-05T03:12:51Z" level=info msg="Creating /proxyrack"
time="2023-04-05T03:13:11Z" level=info msg="Removing image baee8398b570"
time="2023-04-05T03:13:14Z" level=info msg="Session done" Failed=0 Scanned=11 Updated=1 notify=no
time="2023-04-05T05:09:36Z" level=info msg="Session done" Failed=0 Scanned=11 Updated=0 notify=no
time="2023-04-05T07:09:37Z" level=info msg="Session done" Failed=0 Scanned=11 Updated=0 notify=no
time="2023-04-05T09:09:36Z" level=info msg="Session done" Failed=0 Scanned=11 Updated=0 notify=no
time="2023-04-05T11:09:36Z" level=info msg="Session done" Failed=0 Scanned=11 Updated=0 notify=no
time="2023-04-05T13:09:52Z" level=info msg="Session done" Failed=0 Scanned=11 Updated=0 notify=no
time="2023-04-05T15:09:36Z" level=info msg="Session done" Failed=0 Scanned=11 Updated=0 notify=no
time="2023-04-05T17:09:36Z" level=info msg="Session done" Failed=0 Scanned=11 Updated=0 notify=no
time="2023-04-05T19:09:36Z" level=info msg="Session done" Failed=0 Scanned=11 Updated=0 notify=no
time="2023-04-05T21:09:36Z" level=info msg="Session done" Failed=0 Scanned=11 Updated=0 notify=no
~~~
 As i did not see any start command , i've done 
`sudo bash runme.sh`

4 menu item to start apps => here are the logs 

~~~
This menu item will launch all the apps using the configured .env file and the docker-compose.yaml file (Docker must be already installed and running)
Do you wish to proceed Y/N?  y
[+] Running 9/11
 ⠿ Container watchtower      Running                                                                                                                    0.0s
 ⠿ Container traffmonetizer  Running                                                                                                                    0.0s
 ⠿ Container webdashboard    Running                                                                                                                    0.0s
 ⠿ Container iproyal         Running                                                                                                                    0.0s
 ⠿ Container earnapp         Running                                                                                                                    0.0s
 ⠿ Container packetstream    Running                                                                                                                    0.0s
 ⠿ Container honeygain       Running                                                                                                                    0.0s
 ⠿ Container peer2profit     Running                                                                                                                    0.0s
 ⠿ Container repocket        Running                                                                                                                    0.0s
 ⠹ Container bitping         Recreate                                                                                                                  13.6s
 ⠹ Container proxyrack       Recreate
~~~

**Comment by MRColorR** [comment] 2023-04-07 11:55
In your logs i see msg="Creating /proxyrack"  so could you please tell me what is the exact issue you're experiencing?

The only concern for me is the various timeouts watchtower encounter, but eventually it succeeds. I don't know what is causing it , maybe dockerhub limiting the free unauthenticated polling rate , I know they does this but our polling rate should be slow enough.

**Comment by MRColorR** [comment] 2023-04-07 14:26
It should in fact. Next time dirt of all try to see if the container is up using `docker ps -a ` if it's up see logs and check if one of the latest lines indicate that the device is logged in or if there's an error.

**Comment by dorel14** [comment] 2023-04-07 15:05
OK i'l try this

**Comment by dorel14** [comment] 2023-04-14 16:38
Some news
I get same thing this week with repocket updated on docker ,  watchtower update it but don't restart correctly and then it stopped sharing bandwith until i restart it with the 4 menu in runme.sh

**Comment by MRColorR** [comment] 2023-04-15 08:09
ok thank for the update :) .  Make sure you are running the latest version of the project as some changes have been made by the docker team regarding valid docker compose project names which may affect the upgrade process.

Then if the issue appear again, try to provide the following informations:
- `docker ps -a` output
- a list of containers not working correctly
- last few lines of `docker logs` for each container not working correctly 

this way we can try to narrow down the issue.

**Comment by dorel14** [comment] 2023-04-20 17:10
The issue is still here 
Today repocket updated docker image
![image](https://user-images.githubusercontent.com/10910133/233437850-92b335e3-eae7-435a-b75f-30c202c88a58.png)

watchtower logs 

~~~
time="2023-04-19T09:18:54Z" level=info msg="Found new repocket/repocket:latest image (350382a56ce6)"
time="2023-04-19T09:19:03Z" level=info msg="Stopping /repocket (01f5a9f297d0) with SIGTERM"
time="2023-04-19T09:19:42Z" level=info msg="Creating /repocket"
time="2023-04-19T09:20:11Z" level=info msg="Removing image 457206d0cfd1"
~~~

docker ps -a says everything is up and running 

todays winning 
![image](https://user-images.githubusercontent.com/10910133/233438519-6c503b4d-139f-4a6f-83a9-5569ddf21e42.png)

and my device was not visible on repocket dashboard

to resolve i had to make 

docker stop repocket 
docker rm repocket 

sudo bash runme.sh and select 4 option to recreate and start repocket 

magically after my device appear on the dashboard  and i start win somme money

**Comment by MRColorR** [comment] 2023-04-21 09:15
hello , maybe a good news from repocket team:
"Hi everyone! New version of Repocket Windows, Mac, Linux PC (v1.1.25) and Docker (v1.1.18) is now available: 

Fixed disconnection issues and updates to handle more users. "

**Comment by dorel14** [comment] 2023-04-21 12:03
I've seen this , watchtower also but same thing as tomorrow , repocket stop sharing until i stop / rm  / start

**Comment by MRColorR** [comment] 2023-04-22 09:40
After receiving all this information and doing various checks I believe this is not a problem or money4band as the error does not occur in the code I wrote.
The problem is within repocket itself because "PeerService(8308) -> Stop" appears in the repocket container logs every time this issue occurs and it seem repocket can't recover from this state until a manual restart is performed. I'm developing money4band not repocket and I can't fix this.

I don't know if this weird behavior is due to some weird unexpected interaction between watchtower and repocket. but given the setup of watchtower and its ability to work well with all other apps (and in many other contexts) **I think this bug should be reported to the repocket team (pointing out the use of watchtower to update it)** and fixed on their side. Since their app is relatively new maybe something in the logic of the code encounters an unexpected condition.

I'll close this until we receive information on why repocket behaves like this: I don't know how I could solve a problem that I "don't see" as it happens inside a specific app whose external configuration under normal conditions works.

**Closed by MRColorR** 2023-04-22 09:40 UTC
Labels: invalid
