### ISSUE TITLE
(Extra Apps) TRAFFMONETIZER token error

### ISSUE THREAD

**Issue by OlivierVerhoek** [MRColorR/money4band#68] opened 2023-09-29 09:11 UTC
**Describe the bug**
After pasting the token "nGAkspKZztJ0/COqEOAIyIhlliRlqHBUGjSiny9KCkg=" I get "sed: -e expression #1, char 40: unknown option to `s'"
This results in docker not taking over my token as I see in portainer.
start accept status --token yourTRAFFMONETIZERToken --device-name money4bandv15

Extra info from the guides setup
PLEASE REGISTER ON THE PLATFORMS USING THE LINKS THAT WILL BE PROVIDED, YOU'LL THEN NEED TO ENTER SOME DATA BELOW:
Do you wish to enable and use TRAFFMONETIZER? (Y/N)
y
Go to TRAFFMONETIZER https://traffmonetizer.com/?aff=366499 and register
Use CTRL+Click to open links or copy them:
When you are done press Enter to continue
Find your token inside your TRAFFMONETIZER dashboard/profile.
Example: For traffmonetizer you can fetch it from your dashboard https://app.traffmonetizer.com/dashboard then -> Look for Your application token -> just insert it here (you can also copy and then paste it)
Enter your TRAFFMONETIZER token:
nGAkspKZztJ0/COqEOAIyIhlliRlqHBUGjSiny9KCkg=
sed: -e expression #1, char 40: unknown option to `s'
There are 1 tags supporting arm64 arch for this image
Let's see if latest tag is in there
latest tag does not support arm64 arch but other tags do, the newer tag supporting arm64 will be selected
TRAFFMONETIZER configuration complete, press enter to continue to the next app

**Device (please complete the following information):**
 - Type: RPI Zero V2
 - OS details: dietpi
 - Platform: arm64 (64bit)
 
 **Docker**
 - Docker Compose version: Docker Compose version v2.21.0
 - Docker version: Server: Docker Engine - Community Engine: Version:          24.0.6

**Comment by MRColorR** [comment] 2023-09-29 12:38
I'll look into it in a few hours. Thank you.

**Comment by MRColorR** [comment] 2023-09-29 12:40
What special chars are present in your token, If there are any?

**Comment by OlivierVerhoek** [comment] 2023-09-29 13:36
nGAkspKZztJ0/COqEOAIyIhlliRlqHBUGjSiny9KCkg=

**Comment by MRColorR** [comment] 2023-09-29 17:27
I found that the problem is caused by a code regression introduced yesterday, I'm working on it right now.

**Comment by MRColorR** [comment] 2023-09-30 18:03
@OlivierVerhoek  the fix has been pushed to the extra-app branch, feel free to test the new code. Also, if all goes well, a new stable version will be released within a couple of days

**Closed** 2023-10-02 06:52 UTC
Labels: bug, regression
