### ISSUE TITLE
error menu not showing

### ISSUE THREAD

**Issue by mrphuong186** [MRColorR/money4band#98] opened 2024-11-01 04:39 UTC
![screenshot_1730435812](https://github.com/user-attachments/assets/fd08f646-9693-4591-a211-2f925281e009)
error menu not showing
sometimes have to restart many times to show menu
please guide how to solve
thank you very much

**Comment by MRColorR** [comment] 2024-11-01 11:28
Thank you for reporting this issue.

This is the first time this odd behavior has been reported, and since no errors are popping up, it's quite hard to determine how or if it's related to the code. It seems you might be using a very old release, and something could be blocking the update checker function at startup. Please update your m4b to the latest version, as V3 has been deprecated.

I would also like to point out that we have an issue template in place to guide users in providing all the necessary information to help us understand the environment and the cause of their issues. Unfortunately, your report did not include context such as the Docker version, OS version, OS architecture, etc.

If after updating to the V4 release your issue still occurs:
- Could you please provide these details so we can better assist you?
- Also try to run money4band in debug mode by passing --log-level DEBUG as flag to the main and check the generated logs. 
If your issue is resolved after the update, please let us know and feel free to close the issue.

Thank you for your cooperation.

**Comment by mrphuong186** [comment] 2024-11-02 00:16
> Thank you for reporting this issue.
> 
> This is the first time this odd behavior has been reported, and since no errors are popping up, it's quite hard to determine how or if it's related to the code. It seems you might be using a very old release, and something could be blocking the update checker function at startup. Please update your m4b to the latest version, as V3 has been deprecated.
> 
> I would also like to point out that we have an issue template in place to guide users in providing all the necessary information to help us understand the environment and the cause of their issues. Unfortunately, your report did not include context such as the Docker version, OS version, OS architecture, etc.
> 
> If after updating to the V4 release your issue still occurs:
> 
> * Could you please provide these details so we can better assist you?
> * Also try to run money4band in debug mode by passing --log-level DEBUG as flag to the main and check the generated logs.
>   If your issue is resolved after the update, please let us know and feel free to close the issue.
> 
> Thank you for your cooperation.
thanks for your support
as you said V4 version has no menu error
but because it doesn't have new proxy update function or is it broken like in V3?
and the next problem seems honeygain version 0.8.1 always in state Connected. Waiting for traffic...
in V3 i use honeygain version 0.6.6 it works
and very strange i run more than 1 device and the score received is only equal to 1 device?
please give me a solution, thank you very much.
![screenshot_1730506595](https://github.com/user-attachments/assets/ab9f7170-34ca-4e89-929a-74418960a456)

**Comment by MRColorR** [comment] 2024-11-02 09:13
- Regarding the proxy functions V4 has enhanced proxy support significantly (more details in changelogs and on discord M4B community). Many users are successfully using it in this configuration. If an app does not support proxies and actively blocks proxy IPs, there's not much we can do. This does not mean the proxy is broken, but rather that the app does not support it. Additionally, the proxy in use must be capable of accepting the ports and protocols used by the apps, or they won't work. This is a proxy provider issue, not something we can change on our side.

  - If you have found a bug in the image used in V3 and V4 for running proxies, the issue can be resolved by reporting it to the image developer on their GitHub project. Once the new image is online, Money4Band will use it automatically. If you have identified a bug or error in the logic or have a solution or alternative to a problem you've found with the proxies, please share it with us so we can address it.

- Regarding Honeygain, they do not permit proxies. They accept one device per IP, and your IP must not be banned by Honeygain. As your devices are connected, it could be a networking/routing issue between your network, your ISP network, your DNS provider, and Honeygain. Alternatively, Honeygain may have decided not to send traffic to your devices at the moment. Check the Honeygain container logs to see if there are any errors and report back to Honeygain for further assistance. Additionally, Honeygain started building multiarch images starting from version 0.8.0, but I am still using version 0.6.6. There might be something they are still figuring out with these new images. In the meantime i'll investigate this behavior and if i find something i'll discuss it in the discord community.

This is what i can say with the current information, if there is something i missed please explain and i will try to assist you further.

**Closed** 2024-11-09 07:55 UTC
Labels: documentation, troubleshooting 🔧
